### PR TITLE
assorted fixes towards a release

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
First of all thanks to @emillon for the groundwork getting this package into existence.

This PR extends this package with BSD (macos, FreeBSD, OpenBSD) support, and extends the Linux support with all the distributions that are available in OCaml-CI.

The API is slightly modified (now a X509.Authenticator.t is directly returned), and could be merged and used as is.

Note:
- Failing is always on the fail-early side
- There is no support for revocation lists (it is not clear what to do here with the given limitations)
- There is no windows support (see #4 if you're interested)

Are there any Linux distributions missing? IMHO this fixes #1 (we can open individual issues for Linux distributions that we want to support) #2 #3 and #5 (CI uses alpine, this works, anything to do about #5). Once this is merged, I'd be eager to release to opam-repository (and solve #6), to use this package in conduit-lwt-tls etc.

//cc @mirage/core and of course @emillon - any remarks? approvals? adjustments to the API?

**Review by dinosaure — APPROVED** [review]
For me the API is perfect for your use-cases.

**Comment by mato** [comment]
Is this package intended for use in unikernels somehow (extract certs from host system at build/configure time), or is it just for users of ocaml-tls/mirage-crypto in normal OCaml programs?

**Comment by dinosaure** [comment]
> Is this package intended for use in unikernels somehow (extract certs from host system at build/configure time), or is it just for users of ocaml-tls/mirage-crypto in normal OCaml programs?

I'm not sure but we should be able to use it for unikernels - the question is more about the serialization of certificates between the `config.exe` to `main.ml` but, at least, it will want to fix an old issue when `cohttp` accepts any certificates without checks.

**Comment by aronerben** [comment]
Thanks a lot for the work! The API looks nice and it is convenient that an `X509.Authenticator.t` is returned. A quick question: Why was `Lwt` removed? This implies that all file system operations are now blocking, correct?

**Comment by dinosaure** [comment]
> This implies that all file system operations are now blocking, correct?

Yes, but I don't think that we don't really need `lwt` for such process. In our cases, `bos` is better to interact with an operating system (Linux, *BSD or even Windows) and it provides a nice API which cares of slightly OS-dependent details (such as EINTR).

**Comment by hannesm** [comment]
@mato 
> Is this package intended for use in unikernels somehow

not yet. for use in unikernels I have some ideas. I'd -- instead of using whatever is in the host system at build time (which would make the unikernel output dependent on the host system), use a ca_roots_nss package. For now, this package is to be used with lwt-unix.

@aronerben 
> Why was Lwt removed? This implies that all file system operations are now blocking, correct?

That is correct. For two reasons: (1) the Bos API is so much easier (with respect to error handling etc.) to use, and (2) I'd expect the ca-certs package to be used once at program startup (i.e. read and decode the ca certs file once only), so I'm not too worried about the blocking behaviour (and (2b) this allows us to use ca-certs at top-level directly -- similar to Mirage_crypto_rng_lwt.initialize -- in e.g. cohttp-lwt-unix). If you have demand for a non-blocking ca-certs package, would you mind to describe your scenario? Thanks a lot.

**Comment by hannesm** [comment]
FWIW, I created a separate repository for "extract trust anchors from NSS certdata.txt and use them in a unikernel" at https://github.com/mirage/ca-certs-nss. The main reason is that in there I want to follow the NSS release numbers, and there's no code shared between this repository and the MirageOS unikernel one.

**Comment by aronerben** [comment]
@hannesm  
> If you have demand for a non-blocking ca-certs package, would you mind to describe your scenario?
I've looked into my use-case and utilizing the solution you mentioned in (2) won't require `Lwt` for my situation, so blocking is perfectly fine if it's only during startup. So this API works well. Thank you! :)

**Comment by emillon** [comment]
Thanks for taking care of this!

**Pull request merged**
